/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const extractRoutePath: typeof import('./src/composables/go').extractRoutePath
  const formatMesage: typeof import('./src/composables/messages').formatMesage
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getCustUrl: typeof import('./src/composables/useLocalStore').getCustUrl
  const getLocalStore: typeof import('./src/composables/useLocalStore').getLocalStore
  const getRefreshToken: typeof import('./src/composables/useLocalStore').getRefreshToken
  const getToken: typeof import('./src/composables/useLocalStore').getToken
  const go: typeof import('./src/composables/go').default
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const messages: typeof import('./src/composables/messages').default
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const removeCustUrl: typeof import('./src/composables/useLocalStore').removeCustUrl
  const removeLocalStore: typeof import('./src/composables/useLocalStore').removeLocalStore
  const removeRefreshToken: typeof import('./src/composables/useLocalStore').removeRefreshToken
  const removeToken: typeof import('./src/composables/useLocalStore').removeToken
  const request: typeof import('./src/composables/request').default
  const resolveComponent: typeof import('vue').resolveComponent
  const setActivePinia: typeof import('pinia').setActivePinia
  const setCustUrl: typeof import('./src/composables/useLocalStore').setCustUrl
  const setLocalStore: typeof import('./src/composables/useLocalStore').setLocalStore
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const setRefreshToken: typeof import('./src/composables/useLocalStore').setRefreshToken
  const setToken: typeof import('./src/composables/useLocalStore').setToken
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useComApi: typeof import('./src/composables/useComApi').useComApi
  const useComMessage: typeof import('./src/composables/useComMessage').useComMessage
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDialog: typeof import('./src/composables/dialog/useDialog').default
  const useId: typeof import('vue').useId
  const useImage: typeof import('./src/composables/useImage').useImage
  const useKmlApi: typeof import('./src/composables/useKmlApi').useKmlApi
  const useLink: typeof import('vue-router').useLink
  const useLocalStore: typeof import('./src/composables/useLocalStore').useLocalStore
  const useModal: typeof import('./src/composables/modal/useModal').default
  const useModel: typeof import('vue').useModel
  const useNoti: typeof import('./src/composables/noti/useNoti').default
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTokenRefresh: typeof import('./src/composables/useTokenRefresh').default
  const useTokenStore: typeof import('./src/composables/useLocalStore').useTokenStore
  const useValidate: typeof import('./src/composables/useValidate').useValidate
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { DialogType, DialogActionType, DialogGlobalOptions, DialogOptions, DialogInstanceOptions, DialogContainerApi, DialogApi } from './src/composables/dialog/type.dialog'
  import('./src/composables/dialog/type.dialog')
  // @ts-ignore
  export type { ModalGlobalOptions, ModalOptions, Modal, ModalInstanceOptions, ModalContainerApi, ModalApi } from './src/composables/modal/type.modal'
  import('./src/composables/modal/type.modal')
  // @ts-ignore
  export type { NotiType, NotiPosition, NotiCommonOptions, NotiGlobalOptions, NotiOptions, NotiInstanceOptions, NotiContainerApi, NotiApi } from './src/composables/noti/type.noti'
  import('./src/composables/noti/type.noti')
  // @ts-ignore
  export type { AxiosRequestConfig } from './src/composables/request'
  import('./src/composables/request')
}
