/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllMenuPopup: typeof import('./src/components/layout/AllMenuPopup.vue')['default']
    Auth: typeof import('./src/layouts/auth/index.vue')['default']
    CmAccordion: typeof import('./src/components/common/CmAccordion.vue')['default']
    CmButton: typeof import('./src/components/common/CmButton.vue')['default']
    CmChart: typeof import('./src/components/common/CmChart.vue')['default']
    CmChip: typeof import('./src/components/common/CmChip.vue')['default']
    CmColorpicker: typeof import('./src/components/common/CmColorpicker.vue')['default']
    CmDonutProgress: typeof import('./src/components/common/CmDonutProgress.vue')['default']
    CmDropdown: typeof import('./src/components/common/CmDropdown.vue')['default']
    CmEditor: typeof import('./src/components/common/CmEditor.vue')['default']
    CmGrid: typeof import('./src/components/common/cmGrid/index.vue')['default']
    CmGridColumn: typeof import('./src/components/common/cmGrid/CmGridColumn.vue')['default']
    CmLoader: typeof import('./src/components/common/CmLoader.vue')['default']
    CmMap: typeof import('./src/components/common/cmMap/index.vue')['default']
    CmNoData: typeof import('./src/components/common/CmNoData.vue')['default']
    CmPagination: typeof import('./src/components/common/CmPagination.vue')['default']
    CmSwipeBottomSheet: typeof import('./src/components/common/CmSwipeBottomSheet.vue')['default']
    CmTab: typeof import('./src/components/common/CmTab.vue')['default']
    CmTable: typeof import('./src/components/common/CmTable.vue')['default']
    CmTimer: typeof import('./src/components/common/CmTimer.vue')['default']
    CmToggle: typeof import('./src/components/common/CmToggle.vue')['default']
    CmTooltip: typeof import('./src/components/common/CmTooltip.vue')['default']
    CmTree: typeof import('./src/components/common/cmTree/index.vue')['default']
    CmTreeDragNode: typeof import('./src/components/common/cmTree/CmTreeDragNode.vue')['default']
    CmTreeNode: typeof import('./src/components/common/cmTree/CmTreeNode.vue')['default']
    CmTreeView: typeof import('./src/components/common/cmTree/CmTreeView.vue')['default']
    Default: typeof import('./src/layouts/default/index.vue')['default']
    GoogleMap: typeof import('./src/components/common/cmMap/GoogleMap.vue')['default']
    Guide: typeof import('./src/layouts/guide/index.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    InaviMap: typeof import('./src/components/common/cmMap/InaviMap.vue')['default']
    PageLayout: typeof import('./src/components/layout/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCondition: typeof import('./src/components/layout/SearchCondition.vue')['default']
    VCheckbox: typeof import('./src/components/inputs/VCheckbox.vue')['default']
    VDatepicker: typeof import('./src/components/inputs/VDatepicker.vue')['default']
    VDropdown: typeof import('./src/components/inputs/VDropdown.vue')['default']
    VRadio: typeof import('./src/components/inputs/VRadio.vue')['default']
    VSelect: typeof import('./src/components/inputs/VSelect.vue')['default']
    VTextarea: typeof import('./src/components/inputs/VTextarea.vue')['default']
    VTextfield: typeof import('./src/components/inputs/VTextfield.vue')['default']
  }
}
